name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        working-directory: plugin
        run: ./gradlew build --no-daemon

      - uses: jdx/mise-action@v2
        with:
          version: 2025.7.12
          install_args: "nfpm@2.43.0"
          cache: true
          working_directory: test
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        working-directory: test
        run: ./gradlew nfpm --no-daemon
